- name: enable docker connection port in firewall
  iptables:
    chain: INPUT
    protocol: "{{ item }}"
    jump: ACCEPT
    destination_port: "2375"
    comment: connection port for docker
  with_items:
    - tcp

- name: add remote connect configuration
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    line: "        -H=0.0.0.0:2375 \\"
    regexp: "-H="
    insertafter: ExecStart
  notify: 
    - restart docker daemon

- name: add setting for remote connect to shell
  lineinfile:
    dest: "{{ item }}"
    line: "export DOCKER_HOST=tcp://127.0.0.1:2375"
    regexp: DOCKER_HOST
    create: yes
  with_items:
    - /etc/profile
    - ~/.bashrc

- name: remove setting for tls verify from shell
  lineinfile:
    dest: "{{ item }}"
    regexp: DOCKER_TLS_VERIFY
    state: absent
  with_items:
    - /etc/profile
    - ~/.bashrc

- name: remove setting for certs path from shell
  lineinfile:
    dest: "{{ item }}"
    regexp: DOCKER_CERT_PATH
    state: absent
  with_items:
    - /etc/profile
    - ~/.bashrc